Coding Project/QuizManager/QuizManager/Models/EditQuizViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuizManager.Models
{
    public class EditQuizViewModel
    {
        public Quiz CurrentQuiz { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int PassMark { get; set; }
        public Category Category { get; set; }
        public List<Category> Categories { get; set; }
        public ICollection<Question> Questions { get; set; }

        public Question CurrentQuestion { get; set; }
        public Answer[] CurrentArrayOfAnswers { get; set; }

        private QuizManagerEntities QuizEntities = new QuizManagerEntities();
        public EditQuizViewModel()
        {

        }
        public void SetQuizVariables(Quiz currentQuiz)
        {
            Id = currentQuiz.Id;
            Title = currentQuiz.Title;
            Description = currentQuiz.Description;
            PassMark = currentQuiz.PassMark;
            Category = currentQuiz.Category;
            Questions = currentQuiz.Questions;
            foreach (var question in Questions)
            {
                foreach (var answer in question.Answers)
                {
                    if (answer.Correct == 1)
                    {
                        answer.IsCorrect = true;
                    }
                    else
                    {
                        answer.IsCorrect = false;
                    }
                }
            }
        }
        public void SetQuestionVariables(int questionId)
        {
            CurrentQuestion = QuizEntities.Questions.Where(x => x.Id == questionId).Single();
            CurrentArrayOfAnswers = CurrentQuestion.Answers.ToArray();
            foreach (var answer in CurrentArrayOfAnswers)
            {
                if (answer.Correct == 1)
                {
                    answer.IsCorrect = true;
                }
                else
                {
                    answer.IsCorrect = false;
                }
            }
        }
        public void SaveQuizDetails()
        {
            Quiz currentQuiz = QuizEntities.Quizs.Where(x => x.Id == Id).Single();
            currentQuiz.Title = Title;
            currentQuiz.Description = Description;
            currentQuiz.PassMark = PassMark;
            currentQuiz.Category = QuizEntities.Categories.Where(x => x.Title == Category.Title).Single();
            QuizEntities.SaveChanges();

            Questions = currentQuiz.Questions;
        }
        public void SaveQuestionDetails()
        {
            Question currentQuestion = QuizEntities.Questions.Where(x => x.Id == CurrentQuestion.Id).Single();
            currentQuestion.Quiz = QuizEntities.Quizs.Where(x=>x.Title == CurrentQuiz.Title).Single();
            currentQuestion.Question1 = CurrentQuestion.Question1;
            
            foreach (var answer in currentQuestion.Answers)
            {
                Answer editedAnswer = CurrentArrayOfAnswers.Where(x => x.Id == answer.Id).Single();
                answer.Answer1 = editedAnswer.Answer1;
                answer.Explanation = editedAnswer.Explanation;
                if (editedAnswer.IsCorrect==true)
                {
                    answer.Correct = 1;
                }
                else
                {
                    answer.Correct = 0;
                }
            }
            QuizEntities.SaveChanges();
        }
    }
}

Coding Project/QuizManager/QuizManager/Controllers/QuizAdminController.cs
using QuizManager.Models;
using QuizManager.QuizManagement;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizManager.Controllers
{
    public class QuizAdminController : Controller
    {
        private QuizAdmin quizAdmin = new QuizAdmin();
        private QuizViewModel quizViewModel = new QuizViewModel();
        [Authorize(Roles = "Edit")]
        // GET: Edit Quiz
        public ActionResult EditQuiz(EditQuizViewModel model, string QuizName)
        {
            if (model.Id == 0)
            {
                model.CurrentQuiz = quizViewModel.GetQuizByTitle(QuizName);
                model.SetQuizVariables(model.CurrentQuiz);
            }
            else
            {
                model.SaveQuizDetails();
            }
            model.Categories = quizViewModel.Categories;
            return View(model);
        }

        [Authorize(Roles = "Edit")]
        //GET: Edit Questions
        public ActionResult EditQuestions(EditQuizViewModel model, int QuestionId, string QuizName)
        {
            if (model.CurrentQuestion == null)
            {
                model.CurrentQuiz = quizViewModel.GetQuizByTitle(QuizName);
                model.SetQuestionVariables(QuestionId);
            }
            else
            {
                model.SaveQuestionDetails();
                return RedirectToAction("EditQuiz", new { QuizName = model.CurrentQuiz.Title });
            }
            return View(model);
        }
        [Authorize(Roles = "Edit")]
        //GET: Add Quiz 
        public ActionResult AddQuiz(QuizViewModel model)
        {
            if (model.NewQuizItem == null)
            {
                return View(model);
            }
            else
            {
                quizAdmin.AddQuiz(model.NewQuizItem);
                return RedirectToAction("AddQuestions");
            }
        }
        [Authorize(Roles = "Edit")]
        //GET: Add Questions
        public ActionResult AddQuestions(QuizViewModel model)
        {
            if (model.Question == null)
            {
                return View(model);
            }
            else
            {
                quizAdmin.AddQuestionAndAnswers(model.Question, model.ArrayOfAnswers.ToList());
                return View(model);
            }
        }
        [Authorize(Roles = "Edit")]
        // GET: Add Category
        public ActionResult AddCategory(QuizViewModel model)
        {
            quizAdmin.AddCategory(model.NewCategory.Title);
            return RedirectToAction("AddQuiz");
        }
        [Authorize(Roles = "Edit")]
        public ActionResult FinishQuizCreation()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

Coding Project/QuizManager/QuizManager/Views/QuizAdmin/AddQuestions.cshtml
@using QuizManager.Models
@model QuizViewModel
@{
    ViewBag.Title = "Add Questions";
}

<h2>Add Questions</h2>
<div class="container">
    <div class="row">
        <div class="col-md-12 ">
            @using (Html.BeginForm("AddQuestions", "QuizAdmin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "CheckboxControl" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group ">
                    @Html.LabelFor(m => m.Question, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Question.Question1, new { @class = "form-control" })
                    </div>
                </div>
                <hr />
                <div class="form-group d-inline-flex">
                    <p class="col-md-2 control-label">Answer</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[0].Answer1, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Explanation</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[0].Explanation, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Correct</p>
                    <div class="col-md-2">
                        @Html.CheckBoxFor(m => m.ArrayOfAnswers[0].IsCorrect, new { @class = "" })
                    </div>
                </div>
                <div class="form-group  d-inline-flex">
                    <p class="col-md-2 control-label">Answer</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[1].Answer1, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Explanation</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[1].Explanation, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Correct</p>
                    <div class="col-md-2">
                        @Html.CheckBoxFor(m => m.ArrayOfAnswers[1].IsCorrect, new { @class = "" })
                    </div>
                </div>
                <div class="form-group  d-inline-flex">
                    <p class="col-md-2 control-label">Answer</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[2].Answer1, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Explanation</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[2].Explanation, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Correct</p>
                    <div class="col-md-2">
                        @Html.CheckBoxFor(m => m.ArrayOfAnswers[2].IsCorrect, new { @class = "" })
                    </div>
                </div>
                <div class="form-group  d-inline-flex">
                    <p class="col-md-2 control-label">Answer</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[3].Answer1, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Explanation</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[3].Explanation, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Correct</p>
                    <div class="col-md-2">
                        @Html.CheckBoxFor(m => m.ArrayOfAnswers[3].IsCorrect, new { @class = "" })
                    </div>
                </div>
                <div class="form-group  d-inline-flex">
                    <p class="col-md-2 control-label">Answer</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[4].Answer1, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Explanation</p>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.ArrayOfAnswers[4].Explanation, new { @class = "form-control" })
                    </div>
                    <p class="col-md-2 control-label">Correct</p>
                    <div class="col-md-2">
                        @Html.CheckBoxFor(m => m.ArrayOfAnswers[4].IsCorrect, new { @class = "" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-secondary-click" value="Add Question" id="AddQuestionBtn" />
                    </div>
                </div>
            }
            <br />
            @using (Html.BeginForm("FinishQuizCreation", "QuizAdmin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-primary-click" value="Finish Creating Quiz" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<script src="~/Scripts/custom.js"></script>

Coding Project/QuizManager/QuizManager/Views/QuizAdmin/AddQuiz.cshtml
@using QuizManager.Models
@model QuizViewModel
@{
    ViewBag.Title = "Add Quiz";
}

<h2>Add Category</h2>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            @using (Html.BeginForm("AddCategory", "QuizAdmin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    @Html.LabelFor(m => m.NewCategory.Title, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.NewCategory.Title, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-secondary-click" value="Add New Category" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<h2>Add Quiz</h2>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            @using (Html.BeginForm("AddQuiz", "QuizAdmin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    @Html.LabelFor(m => m.NewQuizItem.Title, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.NewQuizItem.Title, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.NewQuizItem.Description, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.NewQuizItem.Description, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.NewQuizItem.Author, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.NewQuizItem.Author, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.NewQuizItem.PassMark, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.NewQuizItem.PassMark, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <p class="col-md-2 control-label">Category</p>
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.NewQuizItem.Category.Title, new SelectList(Model.Categories.Select(m => m.Title)), "Select Category", new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-primary-click" value="Add New Quiz" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Coding Project/QuizManager/QuizManager/Views/QuizAdmin/EditQuestions.cshtml
@model QuizManager.Models.EditQuizViewModel

@{
    ViewBag.Title = "EditQuestions";
}

<h2>Edit Question</h2>

@using (Html.BeginForm("EditQuestions", "QuizAdmin", new { QuestionId = Model.CurrentQuestion.Id }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "CheckboxControl" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.CurrentQuestion.Id)
        @Html.HiddenFor(m=>m.CurrentQuiz.Title)

        <div class="form-group">
            <div class="d-inline-flex">
                <p>Question</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CurrentQuestion.Question1, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
        @for (int i = 0; i < Model.CurrentArrayOfAnswers.Length; i++)
        {
            @Html.HiddenFor(m=>m.CurrentArrayOfAnswers[i].Id)
            <div class="form-group d-inline-flex">
                <p class="col-md-2 control-label">Answer</p>
                <div class="col-md-5">
                    @Html.EditorFor(m => m.CurrentArrayOfAnswers[i].Answer1, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <p class="col-md-2 control-label">Explanation</p>
                <div class="col-md-5">
                    @Html.EditorFor(m => m.CurrentArrayOfAnswers[i].Explanation, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <p class="col-md-2 control-label">Correct</p>
                <div class="col-md-2">
                    @Html.CheckBoxFor(m => m.CurrentArrayOfAnswers[i].IsCorrect, new { @class = "" })
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary-click" />
            </div>
        </div>
    </div>
}

Coding Project/QuizManager/QuizManager/Views/QuizAdmin/EditQuiz.cshtml
@using QuizManager.Models
@model EditQuizViewModel

@{
    ViewBag.Title = "EditQuiz";
}

<h2>Edit Quiz</h2>

@using (Html.BeginForm("EditQuiz", "QuizAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Quiz Details</h4>
    <hr />
    <div class="form-horizontal d-inline-flex col-12">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group col-2">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group col-3">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group col-2">
            @Html.LabelFor(model => model.PassMark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.PassMark, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group col-3">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(m => m.Category.Title, new SelectList(Model.Categories.Select(m => m.Title)), Model.Category.Title, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group col-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Quiz Details" class="btn btn-primary-click" />
            </div>
        </div>
    </div>
}

    <hr />
        <h4 class="col-md-10">Question Details</h4>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>Question</th>
                <th>Answer</th>
                <th>Explanation</th>
                <th>Correct</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var question in Model.Questions)
            {
                <tr>
                    <td>@question.Question1</td>
                    <td>
                        @foreach (var answer in question.Answers)
                        {
                            <p>@answer.Answer1</p>
                        }
                    </td>
                    <td>
                        @foreach (var answer in question.Answers)
                        {
                            <p>@answer.Explanation</p>
                        }
                    </td>
                    <td>
                        @foreach (var answer in question.Answers)
                        {
                            if (answer.IsCorrect == true)
                            {
                                <p><strong>Correct</strong></p>
                            }
                            else
                            {
                                <p>Incorrect</p>
                            }
                        }
                    </td>
                    <td>@Html.RouteLink("Edit", new { action = "EditQuestions", controller = "QuizAdmin", QuestionId = question.Id, QuizName = Model.Title})</td>
                </tr>
            }
        </tbody>
    </table>